### ISSUE TITLE
Game crashes when pausing when text choices are displayed

### ISSUE THREAD

**Issue by Zero-G-Sys** [LunaTechsDev/Luna-game-pause#2]
As title says, game crashes when unpausing when text choices are displayed. 

A similar problem happened with the script [Call Menu from Krimer](https://forums.rpgmakerweb.com/index.php?threads/call-menu-during-messages.101958/). That allowed to save during text but would break when saving during text choices, but he did manage to solve it, so you can use that as reference.

**Comment by KinoAR** [comment]
Will take a look and update the plugin!

**Comment by KinoAR** [comment]
@Zero-G-Sys  I took a look into it and added a text choice and displayed it on screen. But there was no crash. It does reset the choices though upon leaving the pause screen. Can I get more information on what error you're getting?

**Comment by Maurogch** [comment]
Strange, I just made a new clean project and it still gives me the same error.

`message:"Cannot read property 'bitmap' of undefined"
stack:"TypeError: Cannot read property 'bitmap' of undefined
    at Window_ChoiceList.get (chrome-extension://odlameecjipmbmbejkplpemijjgpljce/js/rpg_core.js:6358:43)
    at Window_ChoiceList.textWidthEx (chrome-extension://odlameecjipmbmbejkplpemijjgpljce/js/rpg_windows.js:3908:42)
    at Window_ChoiceList.maxChoiceWidth (chrome-extension://odlameecjipmbmbejkplpemijjgpljce/js/rpg_windows.js:3899:32)
    at Window_ChoiceList.windowWidth (chrome-extension://odlameecjipmbmbejkplpemijjgpljce/js/rpg_windows.js:3875:22)
    at Window_ChoiceList.Window_Command.initialize (chrome-extension://odlameecjipmbmbejkplpemijjgpljce/js/rpg_windows.js:1302:22)
    at Window_ChoiceList.initialize (chrome-extension://odlameecjipmbmbejkplpemijjgpljce/js/rpg_windows.js:3827:41)
    at new Window_ChoiceList (chrome-extension://odlameecjipmbmbejkplpemijjgpljce/js/rpg_windows.js:3819:21)
    at Window_Message.createSubWindows (chrome-extension://odlameecjipmbmbejkplpemijjgpljce/js/rpg_windows.js:4275:26)
    at Window_Message.initialize (...`

**Comment by Zero-G-Sys** [comment]
Strange, I just made a new clean project and it still gives me the same error. Forgot to mention, but this is on MV.

TypeError: Cannot read property 'bitmap' of undefined
message:"Cannot read property 'bitmap' of undefined"
stack:"TypeError: Cannot read property 'bitmap' of undefined
    at Window_ChoiceList.get (chrome-extension://odlameecjipmbmbejkplpemijjgpljce/js/rpg_core.js:6358:43)
    at Window_ChoiceList.textWidthEx (chrome-extension://odlameecjipmbmbejkplpemijjgpljce/js/rpg_windows.js:3908:42)
    at Window_ChoiceList.maxChoiceWidth (chrome-extension://odlameecjipmbmbejkplpemijjgpljce/js/rpg_windows.js:3899:32)
    at Window_ChoiceList.windowWidth (chrome-extension://odlameecjipmbmbejkplpemijjgpljce/js/rpg_windows.js:3875:22)
    at Window_ChoiceList.Window_Command.initialize (chrome-extension://odlameecjipmbmbejkplpemijjgpljce/js/rpg_windows.js:1302:22)
    at Window_ChoiceList.initialize (chrome-extension://odlameecjipmbmbejkplpemijjgpljce/js/rpg_windows.js:3827:41)
    at new Window_ChoiceList (chrome-extension://odlameecjipmbmbejkplpemijjgpljce/js/rpg_windows.js:3819:21)
    at Window_Message.createSubWindows (chrome-extension://odlameecjipmbmbejkplpemijjgpljce/js/rpg_windows.js:4275:26)
    at Window_Message.initialize (...

**Comment by KinoAR** [comment]
Ah okay I was checking MZ. Lol I'll take another look today and update the MV version asap.

**Comment by KinoAR** [comment]
Okay, should have a fix for this issue very soon. Apologies for the delay;  I was busy handling some other events.

But, we're back to work now and I'll be adding it to the list of things that needs to be fixed for this week.

Regards,
